stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
      - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - data/raw/train.csv
      - data/raw/test.csv
    outs:
      - data/interim

  model_builder:
    cmd: python src/model/model_builder.py
    deps:
      - data\interim\train_preprocessed.csv
      - src/model/model_builder.py
    params:
      - model_builder.n_estimators
      - model_builder.max_features
      - model_builder.learning_rate
      - model_builder.ngram_range
      - model_builder.max_depth
    outs:
      - lgbm_model.pkl
      - tfidf_vectorizer.pkl


  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
      - lgbm_model.pkl
      - tfidf_vectorizer.pkl
      - data/interim/test_preprocessed.csv
      - data/interim/test_preprocessed.csv
      - src/model/model_evaluation.py
    outs:
      - experiment_info.json


  model_registration:
    cmd: python src/model/register_model.py
    deps:
      - src/model/register_model.py
      - experiment_info.json